Find_Package( GDK-PixBuf REQUIRED )
Find_Package( Glib REQUIRED )
Find_Package( Pango REQUIRED )
Find_Package( Cairo REQUIRED )
Find_Package( Freetype2 REQUIRED )
Find_Package( Fontconfig REQUIRED )


IF($ENV{MODEL} STREQUAL "PCLINUX")
        ADD_DEPENDENTS( GDK-PIXBUF GLIB PANGO CAIRO FREETYPE2 FONTCONFIG )
ELSEIF($ENV{MODEL} STREQUAL "SATURN7")
        ADD_DEPENDENTS( GDK-PIXBUF GLIB PANGO CAIRO FREETYPE2 FONTCONFIG )
ELSE()
        Find_Package( Gal REQUIRED )
        ADD_DEPENDENTS( GDK-PIXBUF GLIB PANGO CAIRO FREETYPE2 FONTCONFIG GAL)
ENDIF($ENV{MODEL} STREQUAL "PCLINUX")


IF($ENV{BACKEND} STREQUAL "gles")
        add_definitions(-DGL)
ENDIF($ENV{BACKEND} STREQUAL "gles")
