DEF_OPTIONS(SYS_SYSTEM gtk DEFAULT gtk ON)
DEF_OPTIONS(SYS_CANVAS cairo DEFAULT cairo ON)
DEF_OPTIONS(SYS_HTML cef gtk)
DEF_OPTIONS(SYS_PLAYER vlc )

ADD_BOOST_COMPONENTS(system filesystem thread math_tr1)
ADD_INTERNAL_COMPONENTS(util)

