INCLUDE(CPackConfigCommon)

# Main
SET(CPACK_INSTALLED_DIRECTORIES "${CMAKE_CONFIG_INSTALL_PREFIX};/")

SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")

# Product version & name
SET(CPACK_PACKAGE_FILE_NAME "${PACKAGE_NAME}-${PACKAGE_VERSION}")
SET(CPACK_PACKAGE_NAME      "${PACKAGE_NAME}")

SET(CPACK_PACKAGE_VERSION   "${PACKAGE_VERSION}")
STRING(REPLACE "." ";" VERSION_PARTS "${PACKAGE_VERSION}") # Split the version in its components
LIST(GET VERSION_PARTS 0 CPACK_PACKAGE_VERSION_MAJOR)
LIST(GET VERSION_PARTS 1 CPACK_PACKAGE_VERSION_MINOR)
LIST(GET VERSION_PARTS 2 CPACK_PACKAGE_VERSION_PATCH)

# Product description & maintainer
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${PACKAGE_DESCRIPTION}")
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER   "${PACKAGE_MAINTAINER}")

IF(${UNIX})
	SET(CPACK_DEBIAN_PACKAGE_SHLIBDEPS 1)
ENDIF()

#ignore de headers and libs. Note: CPACK_IGNORE_FILES works with CPACK_INSTALLED_DIRECTORIES defined.
SET(CPACK_IGNORE_FILES "/include/;/lib/;\\\\.h$;\\\\.lib$")
