# Disable DVB for windows
set(DVB_USE_DVB 0)
SET(IO_USE_EV 0)
set(SYS_SYSTEM_USE_X11 0)

# This macro adds the executable for the System
MACRO(add_system_executable PROJECT_NAME PROJECT_NAME_SOURCE_FILES)
    if("${PRE_BUILD_SUBSYSTEM}" STREQUAL "Windows" AND ${CMAKE_BUILD_TYPE} STREQUAL "Release")
	  SetIfEmpty(PRE_BUILD_ICON_NAME "")
	  ADD_EXECUTABLE(${PROJECT_NAME} WIN32 ${${PROJECT_NAME_SOURCE_FILES}} ${PRE_BUILD_ICON_NAME})
    else("${PRE_BUILD_SUBSYSTEM}" STREQUAL "Windows" AND ${CMAKE_BUILD_TYPE} STREQUAL "Release")
	  ADD_EXECUTABLE(${PROJECT_NAME} ${${PROJECT_NAME_SOURCE_FILES}})
    endif("${PRE_BUILD_SUBSYSTEM}" STREQUAL "Windows" AND ${CMAKE_BUILD_TYPE} STREQUAL "Release")
ENDMACRO(add_system_executable)
